export const passportRankings = [
  { Passport: 'South Korea', VisaFree: 114, VisaOnArrival: 41, TotalScore: 155 },
  { Passport: 'Japan', VisaFree: 115, VisaOnArrival: 38, TotalScore: 153 },
  { Passport: 'Singapore', VisaFree: 123, VisaOnArrival: 27, TotalScore: 150 },
  { Passport: 'United Arab Emirates', VisaFree: 114, VisaOnArrival: 36, TotalScore: 150 },
  { Passport: 'New Zealand', VisaFree: 111, VisaOnArrival: 39, TotalScore: 150 },
  { Passport: 'Canada', VisaFree: 111, VisaOnArrival: 37, TotalScore: 148 },
  { Passport: 'Malaysia', VisaFree: 112, VisaOnArrival: 34, TotalScore: 146 },
  { Passport: 'Australia', VisaFree: 104, VisaOnArrival: 42, TotalScore: 146 },
  { Passport: 'United Kingdom', VisaFree: 108, VisaOnArrival: 36, TotalScore: 144 },
  { Passport: 'United States', VisaFree: 108, VisaOnArrival: 36, TotalScore: 144 },
  { Passport: 'Brazil', VisaFree: 107, VisaOnArrival: 36, TotalScore: 143 },
  { Passport: 'Argentina', VisaFree: 104, VisaOnArrival: 38, TotalScore: 142 },
  { Passport: 'Monaco', VisaFree: 104, VisaOnArrival: 38, TotalScore: 142 },
  { Passport: 'Chile', VisaFree: 104, VisaOnArrival: 35, TotalScore: 139 },
  { Passport: 'Hong Kong', VisaFree: 108, VisaOnArrival: 31, TotalScore: 139 },
  { Passport: 'Israel', VisaFree: 103, VisaOnArrival: 33, TotalScore: 136 },
  { Passport: 'San Marino', VisaFree: 99, VisaOnArrival: 37, TotalScore: 136 },
  { Passport: 'Andorra', VisaFree: 97, VisaOnArrival: 37, TotalScore: 134 },
  { Passport: 'Barbados', VisaFree: 100, VisaOnArrival: 31, TotalScore: 131 },
  { Passport: 'Mexico', VisaFree: 96, VisaOnArrival: 33, TotalScore: 129 },
  { Passport: 'Brunei', VisaFree: 98, VisaOnArrival: 30, TotalScore: 128 },
  { Passport: 'Bahamas', VisaFree: 96, VisaOnArrival: 32, TotalScore: 128 },
  { Passport: 'Uruguay', VisaFree: 93, VisaOnArrival: 34, TotalScore: 127 },
  { Passport: 'Ukraine', VisaFree: 87, VisaOnArrival: 39, TotalScore: 126 },
  { Passport: 'Peru', VisaFree: 88, VisaOnArrival: 37, TotalScore: 125 },
  { Passport: 'Seychelles', VisaFree: 94, VisaOnArrival: 30, TotalScore: 124 },
  { Passport: 'Vatican', VisaFree: 90, VisaOnArrival: 34, TotalScore: 124 },
  { Passport: 'Costa Rica', VisaFree: 89, VisaOnArrival: 34, TotalScore: 123 },
  { Passport: 'Paraguay', VisaFree: 85, VisaOnArrival: 38, TotalScore: 123 },
  { Passport: 'Saint Vincent and the Grenadines', VisaFree: 91, VisaOnArrival: 30, TotalScore: 121 },
  { Passport: 'Macao', VisaFree: 90, VisaOnArrival: 30, TotalScore: 120 },
  { Passport: 'Denmark', VisaFree: 89, VisaOnArrival: 31, TotalScore: 120 },
  { Passport: 'Spain', VisaFree: 89, VisaOnArrival: 31, TotalScore: 120 },
  { Passport: 'Saint Kitts and Nevis', VisaFree: 91, VisaOnArrival: 29, TotalScore: 120 },
  { Passport: 'Norway', VisaFree: 85, VisaOnArrival: 34, TotalScore: 119 },
  { Passport: 'Switzerland', VisaFree: 85, VisaOnArrival: 34, TotalScore: 119 },
  { Passport: 'Italy', VisaFree: 88, VisaOnArrival: 31, TotalScore: 119 },
  { Passport: 'Sweden', VisaFree: 89, VisaOnArrival: 30, TotalScore: 119 },
  { Passport: 'Panama', VisaFree: 86, VisaOnArrival: 33, TotalScore: 119 },
  { Passport: 'Finland', VisaFree: 89, VisaOnArrival: 30, TotalScore: 119 },
  { Passport: 'Trinidad and Tobago', VisaFree: 93, VisaOnArrival: 26, TotalScore: 119 },
  { Passport: 'France', VisaFree: 89, VisaOnArrival: 30, TotalScore: 119 },
  { Passport: 'Netherlands', VisaFree: 87, VisaOnArrival: 31, TotalScore: 118 },
  { Passport: 'Austria', VisaFree: 86, VisaOnArrival: 32, TotalScore: 118 },
  { Passport: 'Belgium', VisaFree: 88, VisaOnArrival: 30, TotalScore: 118 },
  { Passport: 'Antigua and Barbuda', VisaFree: 88, VisaOnArrival: 30, TotalScore: 118 },
  { Passport: 'Serbia', VisaFree: 84, VisaOnArrival: 34, TotalScore: 118 },
  { Passport: 'Luxembourg', VisaFree: 87, VisaOnArrival: 31, TotalScore: 118 },
  { Passport: 'Portugal', VisaFree: 87, VisaOnArrival: 31, TotalScore: 118 },
  { Passport: 'Greece', VisaFree: 85, VisaOnArrival: 32, TotalScore: 117 },
  { Passport: 'Germany', VisaFree: 86, VisaOnArrival: 31, TotalScore: 117 },
  { Passport: 'Ireland', VisaFree: 81, VisaOnArrival: 36, TotalScore: 117 },
  { Passport: 'Hungary', VisaFree: 82, VisaOnArrival: 34, TotalScore: 116 },
  { Passport: 'Poland', VisaFree: 83, VisaOnArrival: 33, TotalScore: 116 },
  { Passport: 'Czech Republic', VisaFree: 82, VisaOnArrival: 34, TotalScore: 116 },
  { Passport: 'Mauritius', VisaFree: 89, VisaOnArrival: 27, TotalScore: 116 },
  { Passport: 'Slovakia', VisaFree: 81, VisaOnArrival: 34, TotalScore: 115 },
  { Passport: 'Croatia', VisaFree: 81, VisaOnArrival: 34, TotalScore: 115 },
  { Passport: 'Slovenia', VisaFree: 81, VisaOnArrival: 33, TotalScore: 114 },
  { Passport: 'Romania', VisaFree: 80, VisaOnArrival: 34, TotalScore: 114 },
  { Passport: 'Latvia', VisaFree: 80, VisaOnArrival: 34, TotalScore: 114 },
  { Passport: 'Malta', VisaFree: 84, VisaOnArrival: 30, TotalScore: 114 },
  { Passport: 'Liechtenstein', VisaFree: 77, VisaOnArrival: 37, TotalScore: 114 },
  { Passport: 'Bulgaria', VisaFree: 79, VisaOnArrival: 35, TotalScore: 114 },
  { Passport: 'Estonia', VisaFree: 80, VisaOnArrival: 34, TotalScore: 114 },
  { Passport: 'Colombia', VisaFree: 81, VisaOnArrival: 32, TotalScore: 113 },
  { Passport: 'Lithuania', VisaFree: 79, VisaOnArrival: 34, TotalScore: 113 },
  { Passport: 'Cyprus', VisaFree: 83, VisaOnArrival: 30, TotalScore: 113 },
  { Passport: 'Iceland', VisaFree: 77, VisaOnArrival: 36, TotalScore: 113 },
  { Passport: 'North Macedonia', VisaFree: 77, VisaOnArrival: 35, TotalScore: 112 },
  { Passport: 'El Salvador', VisaFree: 78, VisaOnArrival: 34, TotalScore: 112 },
  { Passport: 'Saint Lucia', VisaFree: 83, VisaOnArrival: 29, TotalScore: 112 },
  { Passport: 'Georgia', VisaFree: 72, VisaOnArrival: 39, TotalScore: 111 },
  { Passport: 'Grenada', VisaFree: 83, VisaOnArrival: 28, TotalScore: 111 },
  { Passport: 'Montenegro', VisaFree: 76, VisaOnArrival: 34, TotalScore: 110 },
  { Passport: 'Guatemala', VisaFree: 77, VisaOnArrival: 33, TotalScore: 110 },
  { Passport: 'Solomon Islands', VisaFree: 80, VisaOnArrival: 29, TotalScore: 109 },
  { Passport: 'Honduras', VisaFree: 77, VisaOnArrival: 31, TotalScore: 108 },
  { Passport: 'Venezuela', VisaFree: 69, VisaOnArrival: 38, TotalScore: 107 },
  { Passport: 'Samoa', VisaFree: 77, VisaOnArrival: 30, TotalScore: 107 },
  { Passport: 'Tuvalu', VisaFree: 76, VisaOnArrival: 30, TotalScore: 106 },
  { Passport: 'Turkey', VisaFree: 65, VisaOnArrival: 41, TotalScore: 106 },
  { Passport: 'Taiwan', VisaFree: 71, VisaOnArrival: 34, TotalScore: 105 },
  { Passport: 'Marshall Islands', VisaFree: 71, VisaOnArrival: 33, TotalScore: 104 },
  { Passport: 'Dominica', VisaFree: 77, VisaOnArrival: 27, TotalScore: 104 },
  { Passport: 'Russia', VisaFree: 71, VisaOnArrival: 33, TotalScore: 104 },
  { Passport: 'Nicaragua', VisaFree: 71, VisaOnArrival: 33, TotalScore: 104 },
  { Passport: 'Kiribati', VisaFree: 74, VisaOnArrival: 30, TotalScore: 104 },
  { Passport: 'Bosnia and Herzegovina', VisaFree: 70, VisaOnArrival: 34, TotalScore: 104 },
  { Passport: 'Tonga', VisaFree: 76, VisaOnArrival: 28, TotalScore: 104 },
  { Passport: 'Albania', VisaFree: 71, VisaOnArrival: 31, TotalScore: 102 },
  { Passport: 'Palau', VisaFree: 65, VisaOnArrival: 36, TotalScore: 101 },
  { Passport: 'Micronesia', VisaFree: 66, VisaOnArrival: 34, TotalScore: 100 },
  { Passport: 'Moldova', VisaFree: 65, VisaOnArrival: 33, TotalScore: 98 },
  { Passport: 'Qatar', VisaFree: 61, VisaOnArrival: 31, TotalScore: 92 },
  { Passport: 'South Africa', VisaFree: 53, VisaOnArrival: 33, TotalScore: 86 },
  { Passport: 'Kuwait', VisaFree: 47, VisaOnArrival: 37, TotalScore: 84 },
  { Passport: 'Timor-Leste', VisaFree: 52, VisaOnArrival: 30, TotalScore: 82 },
  { Passport: 'Belize', VisaFree: 55, VisaOnArrival: 26, TotalScore: 81 },
  { Passport: 'Ecuador', VisaFree: 45, VisaOnArrival: 35, TotalScore: 80 },
  { Passport: 'Maldives', VisaFree: 49, VisaOnArrival: 29, TotalScore: 78 },
  { Passport: 'Jamaica', VisaFree: 51, VisaOnArrival: 26, TotalScore: 77 },
  { Passport: 'China', VisaFree: 39, VisaOnArrival: 37, TotalScore: 76 },
  { Passport: 'Kosovo', VisaFree: 47, VisaOnArrival: 27, TotalScore: 74 },
  { Passport: 'Bahrain', VisaFree: 40, VisaOnArrival: 34, TotalScore: 74 },
  { Passport: 'Saudi Arabia', VisaFree: 43, VisaOnArrival: 31, TotalScore: 74 },
  { Passport: 'Indonesia', VisaFree: 43, VisaOnArrival: 31, TotalScore: 74 },
  { Passport: 'Thailand', VisaFree: 37, VisaOnArrival: 37, TotalScore: 74 },
  { Passport: 'Vanuatu', VisaFree: 42, VisaOnArrival: 32, TotalScore: 74 },
  { Passport: 'Fiji', VisaFree: 44, VisaOnArrival: 30, TotalScore: 74 },
  { Passport: 'Belarus', VisaFree: 36, VisaOnArrival: 37, TotalScore: 73 },
  { Passport: 'Guyana', VisaFree: 42, VisaOnArrival: 29, TotalScore: 71 },
  { Passport: 'Oman', VisaFree: 37, VisaOnArrival: 34, TotalScore: 71 },
  { Passport: 'Kazakhstan', VisaFree: 33, VisaOnArrival: 36, TotalScore: 69 },
  { Passport: 'Nauru', VisaFree: 39, VisaOnArrival: 30, TotalScore: 69 },
  { Passport: 'Bolivia', VisaFree: 32, VisaOnArrival: 35, TotalScore: 67 },
  { Passport: 'Dominican Republic', VisaFree: 29, VisaOnArrival: 37, TotalScore: 66 },
  { Passport: 'Botswana', VisaFree: 41, VisaOnArrival: 24, TotalScore: 65 },
  { Passport: 'Papua New Guinea', VisaFree: 33, VisaOnArrival: 32, TotalScore: 65 },
  { Passport: 'Suriname', VisaFree: 32, VisaOnArrival: 33, TotalScore: 65 },
  { Passport: 'Lesotho', VisaFree: 39, VisaOnArrival: 25, TotalScore: 64 },
  { Passport: 'Kenya', VisaFree: 34, VisaOnArrival: 29, TotalScore: 63 },
  { Passport: 'Morocco', VisaFree: 32, VisaOnArrival: 31, TotalScore: 63 },
  { Passport: 'Azerbaijan', VisaFree: 27, VisaOnArrival: 36, TotalScore: 63 },
  { Passport: 'Armenia', VisaFree: 28, VisaOnArrival: 34, TotalScore: 62 },
  { Passport: 'Mongolia', VisaFree: 34, VisaOnArrival: 28, TotalScore: 62 },
  { Passport: 'Swaziland', VisaFree: 36, VisaOnArrival: 25, TotalScore: 61 },
  { Passport: 'Namibia', VisaFree: 34, VisaOnArrival: 27, TotalScore: 61 },
  { Passport: 'Malawi', VisaFree: 35, VisaOnArrival: 26, TotalScore: 61 },
  { Passport: 'Philippines', VisaFree: 33, VisaOnArrival: 27, TotalScore: 60 },
  { Passport: 'Tanzania', VisaFree: 37, VisaOnArrival: 23, TotalScore: 60 },
  { Passport: 'Tunisia', VisaFree: 29, VisaOnArrival: 31, TotalScore: 60 },
  { Passport: 'Uganda', VisaFree: 29, VisaOnArrival: 28, TotalScore: 57 },
  { Passport: 'Sao Tome and Principe', VisaFree: 23, VisaOnArrival: 34, TotalScore: 57 },
  { Passport: 'Zambia', VisaFree: 33, VisaOnArrival: 24, TotalScore: 57 },
  { Passport: 'Rwanda', VisaFree: 23, VisaOnArrival: 33, TotalScore: 56 },
  { Passport: 'Uzbekistan', VisaFree: 24, VisaOnArrival: 32, TotalScore: 56 },
  { Passport: 'Kyrgyzstan', VisaFree: 21, VisaOnArrival: 35, TotalScore: 56 },
  { Passport: 'Cuba', VisaFree: 25, VisaOnArrival: 30, TotalScore: 55 },
  { Passport: 'Madagascar', VisaFree: 26, VisaOnArrival: 29, TotalScore: 55 },
  { Passport: 'Gabon', VisaFree: 25, VisaOnArrival: 29, TotalScore: 54 },
  { Passport: 'Zimbabwe', VisaFree: 30, VisaOnArrival: 23, TotalScore: 53 },
  { Passport: 'Equatorial Guinea', VisaFree: 20, VisaOnArrival: 32, TotalScore: 52 },
  { Passport: 'Tajikistan', VisaFree: 19, VisaOnArrival: 32, TotalScore: 51 },
  { Passport: 'Cape Verde', VisaFree: 24, VisaOnArrival: 27, TotalScore: 51 },
  { Passport: 'India', VisaFree: 22, VisaOnArrival: 28, TotalScore: 50 },
  { Passport: 'Ghana', VisaFree: 28, VisaOnArrival: 22, TotalScore: 50 },
  { Passport: 'Mozambique', VisaFree: 24, VisaOnArrival: 26, TotalScore: 50 },
  { Passport: 'Comoros', VisaFree: 15, VisaOnArrival: 34, TotalScore: 49 },
  { Passport: 'Gambia', VisaFree: 27, VisaOnArrival: 21, TotalScore: 48 },
  { Passport: 'Chad', VisaFree: 21, VisaOnArrival: 27, TotalScore: 48 },
  { Passport: 'Benin', VisaFree: 21, VisaOnArrival: 27, TotalScore: 48 },
  { Passport: 'Cambodia', VisaFree: 19, VisaOnArrival: 29, TotalScore: 48 },
  { Passport: 'Mauritania', VisaFree: 21, VisaOnArrival: 27, TotalScore: 48 },
  { Passport: 'Egypt', VisaFree: 16, VisaOnArrival: 31, TotalScore: 47 },
  { Passport: 'Bhutan', VisaFree: 14, VisaOnArrival: 33, TotalScore: 47 },
  { Passport: 'Algeria', VisaFree: 16, VisaOnArrival: 31, TotalScore: 47 },
  { Passport: 'Central African Republic', VisaFree: 18, VisaOnArrival: 28, TotalScore: 46 },
  { Passport: 'Vietnam', VisaFree: 21, VisaOnArrival: 25, TotalScore: 46 },
  { Passport: 'Cameroon', VisaFree: 19, VisaOnArrival: 26, TotalScore: 45 },
  { Passport: 'Burkina Faso', VisaFree: 20, VisaOnArrival: 25, TotalScore: 45 },
  { Passport: 'Turkmenistan', VisaFree: 12, VisaOnArrival: 33, TotalScore: 45 },
  { Passport: 'Jordan', VisaFree: 17, VisaOnArrival: 28, TotalScore: 45 },
  { Passport: 'Sierra Leone', VisaFree: 25, VisaOnArrival: 20, TotalScore: 45 },
  { Passport: 'Angola', VisaFree: 19, VisaOnArrival: 25, TotalScore: 44 },
  { Passport: 'Haiti', VisaFree: 13, VisaOnArrival: 31, TotalScore: 44 },
  { Passport: 'Djibouti', VisaFree: 14, VisaOnArrival: 30, TotalScore: 44 },
  { Passport: 'Congo', VisaFree: 18, VisaOnArrival: 26, TotalScore: 44 },
  { Passport: 'Togo', VisaFree: 18, VisaOnArrival: 26, TotalScore: 44 },
  { Passport: 'Burundi', VisaFree: 15, VisaOnArrival: 28, TotalScore: 43 },
  { Passport: 'Laos', VisaFree: 18, VisaOnArrival: 25, TotalScore: 43 },
  { Passport: 'Guinea', VisaFree: 17, VisaOnArrival: 25, TotalScore: 42 },
  { Passport: 'Senegal', VisaFree: 19, VisaOnArrival: 22, TotalScore: 41 },
  { Passport: 'Ivory Coast', VisaFree: 17, VisaOnArrival: 24, TotalScore: 41 },
  { Passport: 'Ethiopia', VisaFree: 10, VisaOnArrival: 31, TotalScore: 41 },
  { Passport: 'DR Congo', VisaFree: 14, VisaOnArrival: 26, TotalScore: 40 },
  { Passport: 'Niger', VisaFree: 18, VisaOnArrival: 22, TotalScore: 40 },
  { Passport: 'Lebanon', VisaFree: 12, VisaOnArrival: 28, TotalScore: 40 },
  { Passport: 'South Sudan', VisaFree: 14, VisaOnArrival: 25, TotalScore: 39 },
  { Passport: 'Iran', VisaFree: 12, VisaOnArrival: 27, TotalScore: 39 },
  { Passport: 'Myanmar', VisaFree: 11, VisaOnArrival: 27, TotalScore: 38 },
  { Passport: 'Sri Lanka', VisaFree: 17, VisaOnArrival: 21, TotalScore: 38 },
  { Passport: 'Guinea-Bissau', VisaFree: 15, VisaOnArrival: 23, TotalScore: 38 },
  { Passport: 'Mali', VisaFree: 18, VisaOnArrival: 19, TotalScore: 37 },
  { Passport: 'Eritrea', VisaFree: 10, VisaOnArrival: 27, TotalScore: 37 },
  { Passport: 'Libya', VisaFree: 11, VisaOnArrival: 25, TotalScore: 36 },
  { Passport: 'Sudan', VisaFree: 10, VisaOnArrival: 26, TotalScore: 36 },
  { Passport: 'North Korea', VisaFree: 6, VisaOnArrival: 29, TotalScore: 35 },
  { Passport: 'Liberia', VisaFree: 13, VisaOnArrival: 21, TotalScore: 34 },
  { Passport: 'Nepal', VisaFree: 9, VisaOnArrival: 25, TotalScore: 34 },
  { Passport: 'Palestine', VisaFree: 10, VisaOnArrival: 23, TotalScore: 33 },
  { Passport: 'Bangladesh', VisaFree: 14, VisaOnArrival: 17, TotalScore: 31 },
  { Passport: 'Nigeria', VisaFree: 15, VisaOnArrival: 16, TotalScore: 31 },
  { Passport: 'Yemen', VisaFree: 6, VisaOnArrival: 24, TotalScore: 30 },
  { Passport: 'Somalia', VisaFree: 8, VisaOnArrival: 21, TotalScore: 29 },
  { Passport: 'Pakistan', VisaFree: 8, VisaOnArrival: 20, TotalScore: 28 },
  { Passport: 'Iraq', VisaFree: 7, VisaOnArrival: 20, TotalScore: 27 },
  { Passport: 'Syria', VisaFree: 5, VisaOnArrival: 19, TotalScore: 24 },
  { Passport: 'Afghanistan', VisaFree: 3, VisaOnArrival: 20, TotalScore: 23 },
];